---
- hosts: "{{target}}"
  tasks:
    - name: install helloweb
      docker_container:
        name: helloweb
        image: yodamien0/helloweb
        ports:
          - 81:80
      when: (ansible_distribution == "Centos" or ansible_os-family == "RedHat")
