---
- hosts: "{{target}}"
  tasks:
    - name: LAMP installation Debian/Ubuntu
      apt: name={{item}} state=present
      with_items: "{{lamp_packages_deb}}"
      when: ansible_os_family == "Debian"

    - name: LAMP installation Centos/RedHat
      yum: name={{item}} state=present
      with_items: "{{lamp_packages_el}}"
      when: ansible_os_family == "RedHat"
      
    - name: Redémarrage des services Centos/RedHat
      shell: systemctl restart httpd mariadb && systemctl enable httpd mariadb
      when: ansible_os_family == "RedHat"
      
    - name: Ouverture du pare-feu RedHat
      shell: firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --reload
      when: ansible_os_family == "Debian"
